### ISSUE TITLE
Need to Update the Docs or change the API

### ISSUE THREAD

**Issue by Fosol** [bcgov/common-hosted-email-service#120]
#### Describe the bug
CHES has a bug in the API or Docs. When you return a 422 on the EmailMerge endpoint. The response status is a number, not a string. This will result in errors during deserialization.

#### To Reproduce

1. Submit an invalid request to generate the error response model

#### Expected behavior
The documentation states that the status property is a string, but it is returned as a number.

You should just update your documentation as changing it to a string will most likely break any solutions expecting a number.

**Comment by jujaga** [comment]
Resolved in #121
